import math

iso_639_to_eng_name = {
    "ach":  "Acoli",
    "af":  "Afrikaans",
    "am":  "Amharic",
    "am_ET":  "Amharic (Ethiopia)",
    "an":  "Aragonese",
    "ar":  "Arabic",
    "ast":  "Asturian",
    "as_IN":  "Assamese (India)",
    "be":  "Belarusian",
    "bg":  "Bulgarian",
    "bn":  "Bengali",
    "bn_IN":  "Bengali (India)",
    "br":  "Breton",
    "brx":  "Bodo",
    "bs":  "Bosnian",
    "ca":  "Catalan",
    "ca@valencia":  "Catalan (Valencian)",
    "cgg": "Chiga",
    "co": "Corsican",
    "cs": "Czech",
    "cy": "Welsh",
    "da": "Danish",
    "de": "German",
    "el": "Greek, Modern",
    "en_GB": "English",
    "es": "Spanish",
    "es_MX": "Spanish (Mexico)",
    "et": "Estonian",
    "eu": "Basque",
    "fa": "Persian",
    "ff": "Fulah",
    "fi": "Finnish",
    "fr": "French",
    "fur": "Friulian",
    "fy": "Frisian",
    "ga": "Irish",
    "gd": "Gaelic (Scots)",
    "gl": "Galician",
    "gu": "Gujarati",
    "he": "Hebrew",
    "hi": "Hindi",
    "hr": "Croatian",
    "hu": "Hungarian",
    "hy": "Armenian",
    "id": "Indonesian",
    "is": "Icelandic",
    "it": "Italian",
    "ja": "Japanese",
    "ka": "Georgian",
    "kab": "Kabyle",
    "kk": "Kazakh",
    "km": "Khmer",
    "kn": "Kannada",
    "ko": "Korean",
    "ks_IN": "Kashmiri",
    "ku_IQ": "Kurdish",
    "ky": "Kirgyz",
    "lg": "Ganda",
    "lt": "Lithuanian",
    "lv": "Latvian",
    "mai": "Maithili",
    "ml": "Malayalam",
    "mn": "Mongolian",
    "mr": "Marathi",
    "ms": "Malay",
    "nb": "Norwegian Bokmaal",
    "ne": "Nepali",
    "nl": "Dutch",
    "nn": "Norwegian Nynorsk",
    "oc": "Occitan",
    "pa": "Punjabi",
    "pl": "Polish",
    "ps": "Pashto",
    "pt_BR": "Brazilian Portuguese",
    "pt_PT": "Portuguese",
    "ro": "Romanian",
    "ru": "Russian",
    "si": "Sinhala",
    "sk": "Slovak",
    "sl": "Slovenian",
    "sq": "Albanian",
    "sr": "Serbian",
    "sv": "Swedish",
    "ta": "Tamil",
    "te": "Telugu",
    "th": "Thai",
    "tr": "Turkish",
    "tt": "Tatar",
    "ug": "Uighur",
    "uk": "Ukrainian",
    "uz": "Uzbek",
    "vi": "Vietnamese",
    "wa": "Walloon",
    "zh_CN": "Simplified Chinese",
    "zh_TW": "Traditional Chinese",
    "zu": "Zulu"
}

eng_to_iso_639_name = {
    "Acoli":  "ach",
    "Afrikaans":  "af",
    "Amharic":  "am",
    "Amharic (Ethiopia)":  "am_ET",
    "Aragonese":  "an",
    "Arabic":  "ar",
    "Asturian":  "ast",
    "Assamese (India)":  "as_IN",
    "Belarusian":  "be",
    "Bulgarian":  "bg",
    "Bengali":  "bn",
    "Bengali (India)":  "bn_IN",
    "Breton":  "br",
    "Bodo":  "brx",
    "Bosnian":  "bs",
    "Catalan":  "ca",
    "Catalan (Valencian)":  "ca@valencia",
    "Chiga":  "cgg",
    "Corsican":  "co",
    "Czech":  "cs",
    "Welsh":  "cy",
    "Danish":  "da",
    "German":  "de",
    "Greek, Modern":  "el",
    "English":  "en_GB",
    "Spanish":  "es",
    "Spanish (Mexico)":  "es_MX",
    "Estonian":  "et",
    "Basque":  "eu",
    "Persian":  "fa",
    "Fulah":  "ff",
    "Finnish":  "fi",
    "French":  "fr",
    "Friulian":  "fur",
    "Frisian":  "fy",
    "Irish":  "ga",
    "Gaelic (Scots)":  "gd",
    "Galician":  "gl",
    "Gujarati":  "gu",
    "Hebrew":  "he",
    "Hindi":  "hi",
    "Croatian":  "hr",
    "Hungarian":  "hu",
    "Armenian":  "hy",
    "Indonesian":  "id",
    "Icelandic":  "is",
    "Italian":  "it",
    "Japanese":  "ja",
    "Georgian":  "ka",
    "Kabyle":  "kab",
    "Kazakh":  "kk",
    "Khmer":  "km",
    "Kannada":  "kn",
    "Korean":  "ko",
    "Kashmiri":  "ks_IN",
    "Kurdish":  "ku_IQ",
    "Kirgyz":  "ky",
    "Ganda":  "lg",
    "Lithuanian":  "lt",
    "Latvian":  "lv",
    "Maithili":  "mai",
    "Malayalam":  "ml",
    "Mongolian":  "mn",
    "Marathi":  "mr",
    "Malay":  "ms",
    "Norwegian Bokmaal":  "nb",
    "Nepali":  "ne",
    "Dutch":  "nl",
    "Norwegian Nynorsk":  "nn",
    "Occitan":  "oc",
    "Punjabi":  "pa",
    "Polish":  "pl",
    "Pashto":  "ps",
    "Brazilian Portuguese":  "pt_BR",
    "Portuguese":  "pt_PT",
    "Romanian":  "ro",
    "Russian":  "ru",
    "Sinhala":  "si",
    "Slovak":  "sk",
    "Slovenian":  "sl",
    "Albanian":  "sq",
    "Serbian":  "sr",
    "Swedish":  "sv",
    "Tamil":  "ta",
    "Telugu":  "te",
    "Thai":  "th",
    "Turkish":  "tr",
    "Tatar":  "tt",
    "Uighur":  "ug",
    "Ukrainian":  "uk",
    "Uzbek":  "uz",
    "Vietnamese":  "vi",
    "Walloon":  "wa",
    "Simplified Chinese":  "zh_CN",
    "Traditional Chinese":  "zh_TW",
    "Zulu":  "zu"
}

languages_with_region = {
    "am_ET",
    "as_IN",
    "ca@valencia",
    "es_MX",
    "ks_IN",
    "ku_IQ",
    "pt_BR",
    "pt_PT",
    "zh_CN",
    "zh_TW",
}
